#pragma once
#ifndef _SPRITE_ACTIONS_
#define _SPRITE_ACTIONS_

enum SpriteAction
{
	ACTION_STATIC_UP,
	ACTION_STATIC_DOWN,
	ACTION_STATIC_LEFT,
	ACTION_STATIC_RIGHT,
	ACTION_STATIC_UP_LEFT,
	ACTION_STATIC_DOWN_LEFT,
	ACTION_STATIC_DOWN_RIGHT,
	ACTION_STATIC_UP_RIGHT,
	ACTION_MOVE_UP,
	ACTION_MOVE_DOWN,
	ACTION_MOVE_LEFT,
	ACTION_MOVE_RIGHT,
	ACTION_MOVE_UP_LEFT,
	ACTION_MOVE_DOWN_LEFT,
	ACTION_MOVE_DOWN_RIGHT,
	ACTION_MOVE_UP_RIGHT,
	ACTION_SHOT_UP,
	ACTION_SHOT_DOWN,
	ACTION_SHOT_LEFT,
	ACTION_SHOT_RIGHT,
	ACTION_SHOT_UP_LEFT,
	ACTION_SHOT_DOWN_LEFT,
	ACTION_SHOT_DOWN_RIGHT,
	ACTION_SHOT_UP_RIGHT,
	ACTION_DIE_UP,
	ACTION_DIE_DOWN,
	ACTION_DIE_LEFT,
	ACTION_DIE_RIGHT,
	ACTION_DIE_UP_LEFT,
	ACTION_DIE_DOWN_LEFT,
	ACTION_DIE_DOWN_RIGHT,
	ACTION_DIE_UP_RIGHT
};

#endif